# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoyaEx' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MoyaEx
pod 'Moya'
pod 'Kingfisher'
pod 'SwiftLint'
    target 'MoyaExTests' do
       pod 'Moya'
    end

end
